### ISSUE TITLE
Review CFT parameter help links

### ISSUE THREAD

**Issue by roncewind** [senzing-garage/aws-cloudformation-ecs-senzing-stack-basic#45]
Every CFT parameter help link that I've tried has been a broken link.  For example:  https://hub.senzing.com/aws-cloudformation-ecs-senzing-stack-basic/#senzinglicenseasbase64. We should review the help for each parameter and provide clear instructions and relevant links as needed.

See https://github.com/Senzing/aws-cloudformation-database-cluster/issues/17

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/pull/50

**Comment by docktermj** [comment]
@missulmer Here are the links for your review:

1. **Introductory:** https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/main/README.md
2. **Detailed:** https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/main/docs/README.md (which is also visible at https://hub.senzing.com/aws-cloudformation-ecs-senzing-stack-basic/)
